name: Bug Report
description: File a bug report
title: ''
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen? If you have any screenshots of the issue, please upload them.
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: dropdown
    id: devices
    attributes:
      label: What device are you seeing the problem on?
      multiple: true
      options:
        - Mobile
        - PC
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  name: 🐞 Bug Report
description: File a bug report
title: "[Bug]: <title>"
labels: ["bug"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        ## Thanks for taking the time to fill out this bug report! 👋
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce the bug
      description: Please describe the steps to follow to reproduce the bug you encountered.
      placeholder: "1. Go to '...' \n2. Click on '....' \n3. See error"
      value: ""
    validations:
      required: true
  - type: dropdown
    id: branch
    attributes:
      label: On what branch did you see this bug?
      multiple: true
      options:
        - dev
        - test
        - main
        - main-backup
        - other ( a feature-branch )
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Chrome
        - Firefox
        - Safari
        - Microsoft Edge
        - Other ..
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Please copy and paste any relevant log output. \nThis will be automatically formatted into code, so no need for backticks. ( default language is shell )
      render: shell

  - type: markdown
      attributes:
        value: |
           Include screenshots :camera_flash:
           A great free mockup tool you can use is [Excalidraw](https://excalidraw.com)
