name: Feature Request
description: New feature
title: '[Feature]: '
labels: ['feature']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature!
  - type: textarea
    id: what-feature
    attributes:
      label: What is the feature you're proposing?
      placeholder: 'Describe the feature here'
    validations:
      required: true

  - type: textarea
    id: how-feature
    attributes:
      label: How do you envision this feature working?
      placeholder: 'Explain how you think this feature should work'
    validations:
      required: false
